import { Inter } from "next/font/google";
import "./globals.css";
import Project from "./_components/Project";
import Footer from "./_components/Footer";
import Hearder from "./_components/Hearder";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Hearder />
        {children}
        <Project />
        <Footer />
      </body>
      
      
    </html>
  );
}
